// src/pdf.js
import PDFDocument from "pdfkit";

export function buildPdf(inv) {
  const doc = new PDFDocument({ size: "A4", margin: 50 });

  const number = inv.number || "";
  const currency = inv.currency || "EUR";
  const seller = inv.seller || { name: "VIDA SRL", country: "BE", vat_id: "BE0123.456.789" };
  const buyer = inv.buyer || { name: "", country: "" };
  const totals = {
    net: Number(inv.net ?? 0),
    tax: Number(inv.tax ?? 0),
    gross: Number(inv.gross ?? 0),
  };
  const lines = Array.isArray(inv.lines) ? inv.lines : [];

  // Header
  doc.fontSize(16).text(`Invoice ${number}`, { align: "right" });
  doc.moveDown(1);

  // Seller / Buyer
  doc.fontSize(12).text("Seller:", { continued: true }).font("Helvetica-Bold").text(` ${seller.name}`);
  doc.font("Helvetica").text(`Country: ${seller.country || ""}`);
  if (seller.vat_id) doc.text(`VAT: ${seller.vat_id}`);
  doc.moveDown(0.8);

  doc.fontSize(12).text("Buyer:", { continued: true }).font("Helvetica-Bold").text(` ${buyer.name || ""}`);
  doc.font("Helvetica").text(`Country: ${buyer.country || ""}`);
  if (buyer.vat_id) doc.text(`VAT: ${buyer.vat_id}`);
  doc.moveDown(1);

  // Lines
  doc.font("Helvetica-Bold").text("Description", 50, doc.y);
  doc.text("Qty", 350, doc.y, { width: 50, align: "right" });
  doc.text("Price", 400, doc.y, { width: 80, align: "right" });
  doc.text("Line total", 480, doc.y, { width: 80, align: "right" });
  doc.moveDown(0.4);
  doc.font("Helvetica").moveTo(50, doc.y).lineTo(560, doc.y).stroke();
  doc.moveDown(0.6);

  let currY = doc.y;
  for (const ln of lines) {
    const qty = Number(ln.qty ?? 0);
    const price = Number(ln.price ?? 0);
    const lineTotal = qty * price;

    doc.text(String(ln.name || ""), 50, currY, { width: 280 });
    doc.text(qty.toString(), 350, currY, { width: 50, align: "right" });
    doc.text(price.toFixed(2), 400, currY, { width: 80, align: "right" });
    doc.text(lineTotal.toFixed(2), 480, currY, { width: 80, align: "right" });
    currY = doc.y + 6;
  }
  doc.moveDown(1);

  // Totals
  const labelX = 380;
  const valueX = 480;
  const row = (label, value) => {
    doc.text(label, labelX, doc.y, { width: 90, align: "right" });
    doc.text(`${currency} ${value.toFixed(2)}`, valueX, doc.y, { width: 80, align: "right" });
    doc.moveDown(0.4);
  };
  doc.font("Helvetica-Bold");
  row("Net", totals.net);
  row("Tax", totals.tax);
  row("Gross", totals.gross);
  doc.font("Helvetica");

  // Footer
  doc.moveDown(2);
  doc.fontSize(9).fillColor("gray").text("Generated by VIDA MVP", { align: "center" });
  doc.fillColor("black");

  // IMPORTANT: do NOT doc.end() here; the route will end it after piping.
  return doc;
}
